### ISSUE TITLE
Can't add repository to Kodi

### ISSUE THREAD

**Issue by nre-ableton** [chamchenko/repository.chamchenko#1]
I'm not exactly sure how to add this repository to Kodi so that I can get updates to Add-Ons like NBA International. This (GitHub) repo doesn't have any releases, nor a github.io page which could be added to Kodi as a source. For example, see https://github.com/CastagnaIT/repository.castagnait. I tried downloading a zip file for the current contents of `master` and adding it to Kodi itself, but that isn't a format which Kodi recognizes.

If I'm missing something obvious, maybe it would be nice to at least have a README in this repository detailing how it should be installed.

**Comment by chamchenko** [comment]
Hi,
Just download the zip file from [here](https://raw.githubusercontent.com/chamchenko/repository.chamchenko/master/zips/dev/chamchenko-dev/chamchenko-dev-0.0.2.zip)  and install it in your Kodi.

**Comment by avierschrodt** [comment]
My Kodi states "Can't connect" to repo... :-(

**Comment by SamerElhamdo** [comment]
hello any body can check if the repo is. working i need to update it and fix some error and make change for new route on. shahid.net 

 i have this error 
 
 Application Support/Kodi/addons/plugin.video.shahid/resources/lib/main.py", line 15, in <module>
                                                       from .tools import *
                                                     File "/Users/myuser/Library/Application Support/Kodi/addons/plugin.video.shahid/resources/lib/tools.py", line 12, in <module>
                                                       from Crypto.Cipher import AES
                                                   ModuleNotFoundError: No module named 'Crypto'
                                                   -->End of Python script error report<--

**Comment by chamchenko** [comment]
> hello any body can check if the repo is. working i need to update it and fix some error and make change for new route on. shahid.net
> 
> i have this error
> 
> Application Support/Kodi/addons/plugin.video.shahid/resources/lib/main.py", line 15, in from .tools import * File "/Users/myuser/Library/Application Support/Kodi/addons/plugin.video.shahid/resources/lib/tools.py", line 12, in from Crypto.Cipher import AES ModuleNotFoundError: No module named 'Crypto' -->End of Python script error report<--

I saw that you made a fork of this github repository but if you are interested in working on the shahid addon maybe it's better to make a fork of this one  https://github.com/chamchenko/plugin.video.shahid then make the needed changes.
